# Generated by Django 5.2.15 on 2026-07-08 10:24
#
# Migration C of three pipeline migrations (PIPE-10).
# Creates: LeasingPipelineProperty.
# Confirm Migration A (0027_pipeline_v2) and Migration B (0028_pipe7_migration_b)
# have been applied before running this.
# Do not apply without paruff review.
#

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_pipe7_migration_b"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeasingPipelineProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("LISTING", "Listed / Marketing"),
                            ("SHOWING", "Showings Scheduled"),
                            ("APPLICATION", "Application Received"),
                            ("SCREENING", "Applicant Screening"),
                            ("APPROVED", "Applicant Approved"),
                            ("LEASE_SIGNED", "Lease Signed"),
                            ("MOVE_IN", "Move-In Complete"),
                            ("STABILIZED", "Stabilized"),
                        ],
                        default="LISTING",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("FILLED", "Unit Filled"),
                            ("ON_HOLD", "On Hold"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "asking_rent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("listed_date", models.DateField(blank=True, null=True)),
                (
                    "listing_source",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "applicant_name",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("application_date", models.DateField(blank=True, null=True)),
                ("screening_passed", models.BooleanField(null=True)),
                ("screening_notes", models.TextField(blank=True, default="")),
                ("lease_start_date", models.DateField(blank=True, null=True)),
                ("lease_end_date", models.DateField(blank=True, null=True)),
                (
                    "monthly_rent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "security_deposit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("move_in_date", models.DateField(blank=True, null=True)),
                ("stabilized_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leasing_entries",
                        to="core.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leasing_properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Leasing Pipeline Property",
                "verbose_name_plural": "Leasing Pipeline Properties",
                "ordering": ["-updated_at"],
            },
        ),
    ]
