# Generated by Django 4.2.27 on 2025-12-08 21:15

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=128)),
                ("state", models.CharField(max_length=64)),
                ("zip_code", models.CharField(max_length=16)),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("sqft", models.IntegerField(blank=True, null=True)),
                ("units", models.IntegerField(default=1)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("loan", "Loan"),
                            ("capex", "Capex"),
                            ("opex", "Opex"),
                        ],
                        max_length=16,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date", models.DateField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="core.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RentalIncome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monthly_rent", models.DecimalField(decimal_places=2, max_digits=10)),
                ("effective_date", models.DateField()),
                (
                    "vacancy_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.05"), max_digits=5
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_incomes",
                        to="core.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperatingExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=64)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "frequency",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("annual", "Annual")],
                        default="monthly",
                        max_length=16,
                    ),
                ),
                ("effective_date", models.DateField()),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operating_expenses",
                        to="core.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvestmentAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "noi",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "cap_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "cash_on_cash",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "irr",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "dscr",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=6
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="core.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GrowthArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(db_index=True, max_length=2)),
                ("city_name", models.CharField(max_length=255)),
                ("metro_area", models.CharField(blank=True, max_length=255)),
                (
                    "population_growth_rate",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "employment_growth_rate",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "median_income_growth",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("housing_demand_index", models.IntegerField()),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("data_timestamp", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-data_timestamp"],
                "unique_together": {("state", "city_name")},
            },
        ),
    ]
