# Generated by Django 4.2.27 on 2025-12-08 20:42

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("dummy", "Dummy"), ("external", "External")],
                        max_length=64,
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(blank=True, default="", max_length=128)),
                ("state", models.CharField(blank=True, default="", max_length=64)),
                ("zip_code", models.CharField(blank=True, default="", max_length=16)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("beds", models.PositiveIntegerField(default=0)),
                (
                    "baths",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("0"), max_digits=4
                    ),
                ),
                ("sq_ft", models.PositiveIntegerField(default=0)),
                (
                    "property_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("url", models.URLField(unique=True)),
                ("posted_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-posted_at", "-created_at"],
            },
        ),
    ]
