# Generated by Django 4.2.27 on 2025-12-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_listing"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrowthArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(db_index=True, max_length=2)),
                ("city_name", models.CharField(max_length=255)),
                ("metro_area", models.CharField(blank=True, max_length=255)),
                (
                    "population_growth_rate",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "employment_growth_rate",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "median_income_growth",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("housing_demand_index", models.IntegerField()),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("data_timestamp", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-data_timestamp"],
                "unique_together": {("state", "city_name")},
            },
        ),
    ]
