# Generated by Django 4.2.27 on 2025-12-08 21:51

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_growtharea"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForeclosureProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property_id",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("data_source", models.CharField(max_length=64)),
                ("data_timestamp", models.DateTimeField()),
                ("street", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=128)),
                ("county", models.CharField(blank=True, default="", max_length=128)),
                ("state", models.CharField(db_index=True, max_length=2)),
                ("zip_code", models.CharField(db_index=True, max_length=16)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "foreclosure_status",
                    models.CharField(
                        choices=[
                            ("preforeclosure", "Pre-foreclosure"),
                            ("auction", "Auction Scheduled"),
                            ("reo", "Bank-owned/REO"),
                            ("government", "Government-owned"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "foreclosure_stage",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("filing_date", models.DateField(blank=True, null=True)),
                (
                    "auction_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "auction_time",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("auction_location", models.TextField(blank=True, default="")),
                (
                    "opening_bid",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "unpaid_balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "lender_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "case_number",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "trustee_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "trustee_phone",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "property_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single-family", "Single Family"),
                            ("condo", "Condo"),
                            ("multi-family", "Multi-family"),
                            ("commercial", "Commercial"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                ("bedrooms", models.PositiveIntegerField(default=0)),
                (
                    "bathrooms",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("0"), max_digits=4
                    ),
                ),
                ("square_footage", models.PositiveIntegerField(default=0)),
                ("lot_size", models.PositiveIntegerField(default=0)),
                ("year_built", models.PositiveIntegerField(blank=True, null=True)),
                ("stories", models.PositiveIntegerField(blank=True, null=True)),
                ("garage", models.CharField(blank=True, default="", max_length=128)),
                ("pool", models.BooleanField(default=False)),
                ("condition", models.CharField(blank=True, default="", max_length=64)),
                (
                    "estimated_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "last_sale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("last_sale_date", models.DateField(blank=True, null=True)),
                (
                    "tax_assessed_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "annual_taxes",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("images", models.JSONField(blank=True, default=list)),
                ("property_detail_url", models.URLField(blank=True, default="")),
                ("redfin_url", models.URLField(blank=True, default="")),
                ("zillow_url", models.URLField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["auction_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["state", "city"], name="core_forecl_state_efa6d8_idx"
                    ),
                    models.Index(
                        fields=["foreclosure_status", "auction_date"],
                        name="core_forecl_foreclo_92886b_idx",
                    ),
                ],
            },
        ),
    ]
