# Generated by Django 4.2.27 on 2025-12-09 12:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_notificationpreference_auctionalert_userwatchlist_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_type", models.CharField(default="zip", max_length=16)),
                ("zip_code", models.CharField(blank=True, default="", max_length=16)),
                ("city", models.CharField(blank=True, default="", max_length=128)),
                ("state", models.CharField(blank=True, default="", max_length=64)),
                (
                    "rent_index",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "price_trend",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "crime_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "school_rating",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-price_trend", "-rent_index"],
            },
        ),
    ]
