# Generated by Django 4.2.30 on 2026-05-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_marketsnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketsnapshot",
            name="employment_diversity_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="marketsnapshot",
            name="landlord_friendliness_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="marketsnapshot",
            name="market_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="marketsnapshot",
            name="population_growth_rate",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="marketsnapshot",
            name="price_to_rent_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="marketsnapshot",
            name="rent_growth_rate",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=7, null=True
            ),
        ),
    ]
