# Generated by Django 4.2.30 on 2026-05-18 17:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_savedsearch_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="investmentanalysis",
            name="exit_cap_rate",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.06"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="investmentanalysis",
            name="hold_years",
            field=models.IntegerField(default=5),
        ),
    ]
