# Generated by Django 4.2.30 on 2026-05-18 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def copy_property_user_to_owner(apps, schema_editor):
    Property = apps.get_model("core", "Property")
    Property.objects.filter(owner__isnull=True).update(owner=models.F("user"))


def copy_property_owner_to_user(apps, schema_editor):
    Property = apps.get_model("core", "Property")
    Property.objects.filter(user__isnull=True).update(user=models.F("owner"))


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0009_savedsearch_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legacy_properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(
            copy_property_user_to_owner,
            reverse_code=copy_property_owner_to_user,
        ),
    ]
