# Generated by Django 4.2.30 on 2026-05-19 02:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_investmentanalysis_exit_cap_rate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VrmProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vrm_property_id", models.IntegerField(unique=True)),
                ("vrm_listing_url", models.URLField()),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=128)),
                ("state", models.CharField(max_length=2)),
                ("zip_code", models.CharField(max_length=16)),
                ("county", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "list_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "bedrooms",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "bathrooms",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "square_feet",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "lot_size_sf",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "year_built",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "property_type",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("for_sale", "For Sale"),
                            ("coming_soon", "Coming Soon"),
                            ("pending", "Pending"),
                            ("sold", "Sold"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "listing_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("traditional", "Traditional"),
                            ("online_auction", "Online Auction"),
                            ("in_person_auction", "In-person Auction"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("vendee_eligible", models.BooleanField(default=False)),
                ("occupied", models.BooleanField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("mls_id", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "parcel_number",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "days_on_site",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("scraped_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
            ],
            options={
                "db_table": "vrm_property",
            },
        ),
    ]
