# Generated by Django 4.2.30 on 2026-05-20 02:57

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_vrmproperty"),
    ]

    operations = [
        migrations.AddField(
            model_name="vrmproperty",
            name="annual_expenses",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="vrmproperty",
            name="cap_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=7
            ),
        ),
        migrations.AddField(
            model_name="vrmproperty",
            name="effective_gross_rent",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="vrmproperty",
            name="estimated_rehab",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="vrmproperty",
            name="gross_annual_rent",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="vrmproperty",
            name="meets_profit_target",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vrmproperty",
            name="noi",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="vrmproperty",
            name="profit_margin_pct",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=7
            ),
        ),
        migrations.AddField(
            model_name="vrmproperty",
            name="projected_monthly_rent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="vrmproperty",
            name="total_investment",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
    ]
