# Generated by Django 4.2.27 on 2026-06-18 20:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_propertyshare"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="bathrooms",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="bedrooms",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="capex_monthly",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("100.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="down_payment_pct",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.20"),
                help_text="Fraction (e.g. 0.20 for 20%)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="hoa_monthly",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="insurance_annual",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="interest_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.07"),
                help_text="Annual rate as fraction (e.g. 0.07 for 7%)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="loan_term_years",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="property",
            name="maintenance_monthly",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("150.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="mgmt_fee_pct",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.10"),
                help_text="Fraction (e.g. 0.10 for 10%)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="monthly_rent_gross",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="other_monthly_income",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="property_taxes_annual",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SFR", "Single-Family Residence"),
                    ("duplex", "Duplex"),
                    ("triplex", "Triplex"),
                    ("fourplex", "Fourplex"),
                    ("small_multifamily", "Small Multifamily"),
                ],
                default="SFR",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="vacancy_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.08"),
                help_text="Fraction (e.g. 0.08 for 8%)",
                max_digits=5,
            ),
        ),
    ]
