# Generated by Django 4.2.27 on 2026-06-18 20:50

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_property_bathrooms_property_bedrooms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketsnapshot",
            name="fetched_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this data was fetched from Census/BLS APIs",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketsnapshot",
            name="median_household_income",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Median household income in dollars",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketsnapshot",
            name="msa_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Metropolitan Statistical Area name",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="marketsnapshot",
            name="population",
            field=models.PositiveIntegerField(
                blank=True, help_text="Total population for ZIP/area", null=True
            ),
        ),
        migrations.AddField(
            model_name="marketsnapshot",
            name="population_growth_pct_5yr",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="5-year population growth as fraction (e.g. 0.0234 = 2.34%)",
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketsnapshot",
            name="unemployment_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Unemployment rate as fraction (e.g. 0.045 = 4.5%)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="bathrooms",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="purchase_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
