# Generated by Django 4.2.27 on 2026-06-19 07:29

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0016_add_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInvestmentTargets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_coc_pct",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.08"),
                        help_text="Minimum Cash-on-Cash return as a fraction (e.g. 0.08 for 8 %)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                (
                    "min_dscr",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.25"),
                        help_text="Minimum Debt Service Coverage Ratio (e.g. 1.25)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("10")),
                        ],
                    ),
                ),
                (
                    "max_grm",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("12.00"),
                        help_text="Maximum Gross Rent Multiplier — lower is better (e.g. 12.0)",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "require_one_pct_rule",
                    models.BooleanField(
                        default=True,
                        help_text="If enabled, properties failing the 1% Rule are capped at 40 points",
                    ),
                ),
                ("target_hold_years", models.PositiveIntegerField(default=7)),
                (
                    "annual_rent_growth_assumption",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.03"),
                        help_text="Assumed annual rent growth as a fraction",
                        max_digits=5,
                    ),
                ),
                (
                    "annual_appreciation_assumption",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.03"),
                        help_text="Assumed annual appreciation as a fraction",
                        max_digits=5,
                    ),
                ),
                (
                    "marginal_tax_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.24"),
                        help_text="Marginal income-tax rate as a fraction",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investment_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
