# Generated by Django 5.2.15 on 2026-06-19 09:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_add_userinvestmenttargets"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="growtharea",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="propertyshare",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="sharedproperty",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="teammember",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="userwatchlist",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="growtharea",
            constraint=models.UniqueConstraint(
                fields=("state", "city_name"), name="unique_state_city"
            ),
        ),
        migrations.AddConstraint(
            model_name="propertyshare",
            constraint=models.UniqueConstraint(
                fields=("property", "shared_with"), name="unique_property_shared_with"
            ),
        ),
        migrations.AddConstraint(
            model_name="sharedproperty",
            constraint=models.UniqueConstraint(
                fields=("property", "team"), name="unique_property_team"
            ),
        ),
        migrations.AddConstraint(
            model_name="teammember",
            constraint=models.UniqueConstraint(
                fields=("team", "user"), name="unique_team_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="userwatchlist",
            constraint=models.UniqueConstraint(
                fields=("user", "property"), name="unique_user_watchlist_property"
            ),
        ),
    ]
