# Generated by Django 5.2.15 on 2026-06-19 11:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_convert_unique_together_to_unique_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyActuals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.DateField(help_text="First day of month, e.g. 2026-06-01"),
                ),
                (
                    "actual_rent_collected",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "actual_vacancy_days",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of vacant days in the month"
                    ),
                ),
                (
                    "actual_expenses",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Total operating expenses (taxes, insurance, HOA, etc.)",
                        max_digits=10,
                    ),
                ),
                (
                    "actual_maintenance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Maintenance and repair costs",
                        max_digits=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_actuals",
                        to="core.property",
                    ),
                ),
            ],
            options={
                "ordering": ["-month"],
                "unique_together": {("prop", "month")},
            },
        ),
    ]
