# Generated by Django 5.2.15 on 2026-07-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_add_monthly_actuals"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketsnapshot",
            name="data_source",
            field=models.CharField(
                blank=True,
                default="dummy",
                help_text="Adapter source for this snapshot (e.g. 'rentcast', 'dummy', 'mixed')",
                max_length=64,
            ),
        ),
    ]
