# Generated by Django 5.2.15 on 2026-07-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_add_datasource_to_marketsnapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="growtharea",
            name="employment_growth_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
