# Generated by Django 5.2.15 on 2026-07-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_growtharea_nullable_emp"),
    ]

    operations = [
        migrations.AddField(
            model_name="growtharea",
            name="supply_constraint_index",
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
    ]
