# Generated by Django 5.2.15 on 2026-07-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_growtharea_supply_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="growtharea",
            name="composite_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Precomputed weighted growth score (computed on save)",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="growtharea",
            name="population",
            field=models.IntegerField(
                blank=True, help_text="Latest population from Census ACS", null=True
            ),
        ),
    ]
