# Generated by Django 5.2.15 on 2026-07-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_growtharea_population_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_id",
                    models.CharField(
                        help_text="External source identifier",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("address", models.TextField(help_text="Raw address string")),
                (
                    "address_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 of normalized address for dedup",
                        max_length=64,
                    ),
                ),
                (
                    "source_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Origin source label",
                        max_length=100,
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("GACS", "GACS"),
                            ("DISCOVERY", "Discovery"),
                            ("SCREENING", "Screening"),
                            ("UNDERWRITING", "Underwriting"),
                            ("OFFER", "Offer"),
                            ("DUE_DILIGENCE", "Due Diligence"),
                            ("CLOSING", "Closing"),
                            ("TURNOVER", "Turnover"),
                            ("LEASING", "Leasing"),
                            ("PORTFOLIO", "Portfolio"),
                            ("KILLED", "Killed"),
                        ],
                        default="GACS",
                        max_length=20,
                    ),
                ),
                ("kill_reason", models.TextField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "estimated_rent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "noi",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "cap_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                (
                    "mao",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("beds", models.IntegerField(blank=True, null=True)),
                ("baths", models.FloatField(blank=True, null=True)),
                ("sqft", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pipeline Asset",
                "verbose_name_plural": "Pipeline Assets",
                "ordering": ["-updated_at"],
            },
        ),
    ]
