# Generated by Django 5.2.15 on 2026-07-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_screening_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="growtharea",
            name="landlord_score",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=None,
                help_text="State landlord-friendliness score (0=tenant-friendly, 10=landlord-friendly)",
                null=True,
            ),
        ),
    ]
