# Generated by Django 5.2.15 on 2026-07-08 07:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_growtharea_landlord_score"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScreeningCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "min_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "min_gross_yield_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("7.00"),
                        help_text="Minimum gross yield as percentage (e.g. 7.00 = 7%)",
                        max_digits=5,
                    ),
                ),
                (
                    "max_price_to_rent_ratio",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("15.00"), max_digits=6
                    ),
                ),
                ("min_beds", models.IntegerField(default=1)),
                ("max_beds", models.IntegerField(blank=True, null=True)),
                ("min_sqft", models.IntegerField(blank=True, null=True)),
                ("max_year_built", models.IntegerField(blank=True, null=True)),
                ("allowed_property_types", models.JSONField(blank=True, default=list)),
                ("allowed_states", models.JSONField(blank=True, default=list)),
                (
                    "allowed_foreclosure_statuses",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "min_gacs_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum Growth Area Composite Score for the property's market",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screening_criteria",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Screening Criteria",
                "verbose_name_plural": "Screening Criteria",
            },
        ),
        migrations.CreateModel(
            name="PipelineProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("vrm", "VRM Foreclosure"),
                            ("foreclosure", "County Foreclosure"),
                            ("listing", "MLS Listing"),
                            ("manual", "Manual Entry"),
                            ("hud", "HUD Homestore"),
                            ("usda", "USDA Foreclosure"),
                            ("fannie", "Fannie Mae HomePath"),
                            ("freddie", "Freddie Mac HomeSteps"),
                            ("county", "County Records"),
                            ("bank_reo", "Bank REO"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_id", models.CharField(max_length=255)),
                ("address", models.TextField()),
                (
                    "address_hash",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("DISCOVERED", "Discovered"),
                            ("SCREENING", "Screening"),
                            ("UNDERWRITING", "Underwriting"),
                            ("OFFER", "Offer"),
                            ("DUE_DILIGENCE", "Due Diligence"),
                            ("CLOSING", "Closing"),
                            ("ACQUIRED", "Acquired"),
                            ("RENOVATION", "Renovation"),
                            ("STABILIZED", "Stabilized"),
                        ],
                        default="DISCOVERED",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("KILLED", "Killed"),
                            ("ON_HOLD", "On Hold"),
                            ("ACQUIRED", "Acquired"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("screening_passed", models.BooleanField(blank=True, null=True)),
                ("kill_reason", models.TextField(blank=True, default="")),
                ("discovered_at", models.DateTimeField(blank=True, null=True)),
                ("screening_at", models.DateTimeField(blank=True, null=True)),
                ("underwriting_at", models.DateTimeField(blank=True, null=True)),
                ("offer_at", models.DateTimeField(blank=True, null=True)),
                ("due_diligence_at", models.DateTimeField(blank=True, null=True)),
                ("closing_at", models.DateTimeField(blank=True, null=True)),
                ("acquired_at", models.DateTimeField(blank=True, null=True)),
                ("renovation_at", models.DateTimeField(blank=True, null=True)),
                ("stabilized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "estimated_rent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("beds", models.IntegerField(blank=True, null=True)),
                ("baths", models.FloatField(blank=True, null=True)),
                ("sqft", models.FloatField(blank=True, null=True)),
                ("year_built", models.IntegerField(blank=True, null=True)),
                (
                    "gacs_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "mao",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "investment_analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.investmentanalysis",
                    ),
                ),
                (
                    "property_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline_properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pipeline Property",
                "verbose_name_plural": "Pipeline Properties",
                "ordering": ["-updated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "source_type", "source_id"),
                        name="unique_user_source_property",
                    )
                ],
            },
        ),
    ]
