# Generated by Django 5.2.15 on 2026-07-08 09:43
#
# Migration B of three pipeline migrations (PIPE-7).
# Creates: OfferRecord, DueDiligenceChecklist, ClosingRecord, RenovationRecord.
# Confirm Migration A (0027_pipeline_v2) has been applied before running this.
# Do not apply without paruff review.
#

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_pipeline_v2"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClosingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "final_purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("closing_date", models.DateField()),
                (
                    "closing_costs",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "loan_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "down_payment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("lender", models.CharField(blank=True, default="", max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pipeline_property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closing_record",
                        to="core.pipelineproperty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Closing Record",
                "verbose_name_plural": "Closing Records",
            },
        ),
        migrations.CreateModel(
            name="DueDiligenceChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inspection_scheduled", models.BooleanField(default=False)),
                ("inspection_completed", models.BooleanField(default=False)),
                ("inspection_findings", models.TextField(blank=True, default="")),
                ("title_search_ordered", models.BooleanField(default=False)),
                ("title_clear", models.BooleanField(blank=True, null=True)),
                ("appraisal_ordered", models.BooleanField(default=False)),
                (
                    "appraisal_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("insurance_quoted", models.BooleanField(default=False)),
                (
                    "insurance_annual_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("contractor_estimate_obtained", models.BooleanField(default=False)),
                (
                    "contractor_estimate_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "go_no_go",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("go", "Go"),
                            ("no_go", "No Go"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("no_go_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pipeline_property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="due_diligence",
                        to="core.pipelineproperty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Due Diligence Checklist",
                "verbose_name_plural": "Due Diligence Checklists",
            },
        ),
        migrations.CreateModel(
            name="OfferRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offer_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("offer_date", models.DateField()),
                ("offer_expiry", models.DateField(blank=True, null=True)),
                ("contingencies", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("countered", "Countered"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "counter_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pipeline_property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="core.pipelineproperty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offer Record",
                "verbose_name_plural": "Offer Records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RenovationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estimated_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("completion_date", models.DateField(blank=True, null=True)),
                (
                    "contractor",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("scope_of_work", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("complete", "Complete"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pipeline_property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renovation_record",
                        to="core.pipelineproperty",
                    ),
                ),
                (
                    "property_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="renovations",
                        to="core.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Renovation Record",
                "verbose_name_plural": "Renovation Records",
            },
        ),
    ]
