# Generated by Django 5.2.16 on 2026-07-08 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_pipe10_migration_c"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertySource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("vrm", "VRM Foreclosure"),
                            ("foreclosure", "County Foreclosure"),
                            ("listing", "MLS Listing"),
                            ("manual", "Manual Entry"),
                            ("hud", "HUD Homestore"),
                            ("usda", "USDA Foreclosure"),
                            ("fannie", "Fannie Mae HomePath"),
                            ("freddie", "Freddie Mac HomeSteps"),
                            ("county", "County Records"),
                            ("bank_reo", "Bank REO"),
                        ],
                        help_text="Maps to PipelineProperty.SourceType",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, default="")),
                ("website_url", models.URLField(blank=True, default="")),
                ("is_free", models.BooleanField(default=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Has a working scraper or API integration",
                    ),
                ),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Property Source",
                "verbose_name_plural": "Property Sources",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="DiscoveryRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="City, State or ZIP code to target", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="requested",
                        max_length=16,
                    ),
                ),
                ("properties_found", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discovery_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="core.propertysource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discovery Request",
                "verbose_name_plural": "Discovery Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
