# Generated by Django 5.2.16 on 2026-07-08 17:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_seed_property_sources"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountyForeclosureNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_number",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("nod", "Notice of Default"),
                            ("nts", "Notice of Trustee Sale"),
                            ("sheriff_sale", "Sheriff Sale"),
                            ("lis_pendens", "Lis Pendens"),
                            ("auction", "Auction Calendar"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "borrower_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "lender_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "trustee_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=128)),
                ("state", models.CharField(db_index=True, max_length=2)),
                ("zip_code", models.CharField(blank=True, default="", max_length=16)),
                ("county", models.CharField(db_index=True, max_length=128)),
                ("filing_date", models.DateField(blank=True, null=True)),
                ("sale_date", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "auction_time",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("auction_location", models.TextField(blank=True, default="")),
                (
                    "opening_bid",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "unpaid_balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "parcel_number",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("source_url", models.URLField(blank=True, default="")),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("scraped_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "County Foreclosure Notice",
                "verbose_name_plural": "County Foreclosure Notices",
                "ordering": ["-sale_date", "-filing_date"],
                "indexes": [
                    models.Index(
                        fields=["county", "state"], name="core_county_county_0e910c_idx"
                    ),
                    models.Index(
                        fields=["document_type"], name="core_county_documen_a93ac5_idx"
                    ),
                    models.Index(
                        fields=["sale_date"], name="core_county_sale_da_5d8c5a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HudProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hud_case_number",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=128)),
                ("state", models.CharField(db_index=True, max_length=2)),
                ("zip_code", models.CharField(max_length=16)),
                ("county", models.CharField(blank=True, default="", max_length=128)),
                (
                    "list_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "bedrooms",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "bathrooms",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "square_feet",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "property_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending", "Pending"),
                            ("sold", "Sold"),
                            ("contingent", "Contingent"),
                        ],
                        max_length=32,
                    ),
                ),
                ("listing_url", models.URLField(blank=True, default="")),
                ("image_url", models.URLField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                ("scraped_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "HUD Property",
                "verbose_name_plural": "HUD Properties",
                "indexes": [
                    models.Index(
                        fields=["state", "city"], name="core_hudpro_state_66a937_idx"
                    ),
                    models.Index(
                        fields=["status"], name="core_hudpro_status_a2fdb1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UsdaProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usda_case_number",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=128)),
                ("state", models.CharField(db_index=True, max_length=2)),
                ("zip_code", models.CharField(max_length=16)),
                ("county", models.CharField(blank=True, default="", max_length=128)),
                (
                    "list_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "bedrooms",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "bathrooms",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "square_feet",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "lot_size_acres",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "property_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending", "Pending"),
                            ("sold", "Sold"),
                        ],
                        max_length=32,
                    ),
                ),
                ("listing_url", models.URLField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                ("scraped_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "USDA Property",
                "verbose_name_plural": "USDA Properties",
                "indexes": [
                    models.Index(
                        fields=["state", "city"], name="core_usdapr_state_5f12f6_idx"
                    ),
                    models.Index(
                        fields=["status"], name="core_usdapr_status_e62b76_idx"
                    ),
                ],
            },
        ),
    ]
