# Generated by Django 5.2.16 on 2026-07-08 19:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_disc_0_source_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="hudproperty",
            name="asking_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="hudproperty",
            name="insured_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fha_insured", "FHA Insured"),
                    ("conventional", "Conventional"),
                    ("uninsured", "Uninsured"),
                    ("va", "VA"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="hudproperty",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("pending", "Pending"),
                    ("sold", "Sold"),
                    ("contingent", "Contingent"),
                    ("removed", "Removed"),
                ],
                max_length=32,
            ),
        ),
    ]
