# Generated by Django 5.2.16 on 2026-07-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_disc_0_source_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usdaproperty",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("pending", "Pending"),
                    ("sold", "Sold"),
                    ("removed", "Removed"),
                ],
                max_length=32,
            ),
        ),
    ]
