# Generated by Django 6.0.7 on 2026-07-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_growth_area_enhancements"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_onboarded",
            field=models.BooleanField(
                default=False, help_text="User has completed initial onboarding setup"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("auction_update", "Auction Update"),
                    ("status_change", "Status Change"),
                    ("postponement", "Postponement"),
                    ("reminder", "Reminder"),
                    ("price_change", "Price Change"),
                    ("sold", "Property Sold"),
                    ("pipeline_match", "Pipeline Match"),
                ],
                max_length=32,
            ),
        ),
    ]
