# Generated by Django 6.0.7 on 2026-07-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_userprofile_is_onboarded_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="growtharea",
            name="rent_growth_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="5-year gross rent growth rate — NOT YET POPULATED. Field reserved for HUD FMR or ACS rent growth integration. See GACS-FMR-1 in backlog.",
                max_digits=6,
                null=True,
            ),
        ),
    ]
