# Generated by Django 6.0.7 on 2026-07-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_alter_growtharea_rent_growth_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="growtharea",
            name="county_fips",
            field=models.CharField(
                blank=True,
                default="",
                help_text="5-character county FIPS code for QCEW employment lookup (e.g. '48113' for Dallas County TX)",
                max_length=5,
            ),
        ),
    ]
