# Generated by Django 6.0.7 on 2026-07-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_growtharea_county_fips"),
    ]

    operations = [
        migrations.AddField(
            model_name="growtharea",
            name="fmr_2br",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="HUD FY2026 2BR Fair Market Rent (40th pct rent floor, not market rent)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="growtharea",
            name="fmr_year",
            field=models.IntegerField(
                blank=True,
                help_text="Fiscal year of the FMR data (e.g. 2026)",
                null=True,
            ),
        ),
    ]
