# Generated by Django 6.0.7 on 2026-07-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_growtharea_fmr_2br_growtharea_fmr_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="growtharea",
            name="rent_growth_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Year-over-year 2BR FMR growth rate from HUD (populated by populate_growth_areas via FMR adapter).  Null when HUD_API_KEY is missing or entity ID lookup fails.",
                max_digits=6,
                null=True,
            ),
        ),
    ]
