# Generated by Django 6.0.7 on 2026-07-11 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_alter_growtharea_rent_growth_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelineproperty",
            name="city",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="City name copied from source record at discovery time",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="pipelineproperty",
            name="county",
            field=models.CharField(
                blank=True,
                default="",
                help_text="County name copied from source record — links to QCEW and FMR data",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="pipelineproperty",
            name="growth_area",
            field=models.ForeignKey(
                blank=True,
                help_text="Growth area this property was discovered under — set at discovery time",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pipeline_properties",
                to="core.growtharea",
            ),
        ),
        migrations.AddField(
            model_name="pipelineproperty",
            name="state",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="2-letter state code copied from source record",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="pipelineproperty",
            name="zip_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="ZIP code copied from source record",
                max_length=16,
            ),
        ),
    ]
