# Generated by Django 6.0.7 on 2026-07-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_add_location_fields_to_pipeline_property"),
    ]

    operations = [
        migrations.AlterField(
            model_name="countyforeclosurenotice",
            name="city",
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="pipelineproperty",
            name="screening_passed",
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="pipelineproperty",
            name="stage",
            field=models.CharField(
                choices=[
                    ("DISCOVERED", "Discovered"),
                    ("SCREENING", "Screening"),
                    ("UNDERWRITING", "Underwriting"),
                    ("OFFER", "Offer"),
                    ("DUE_DILIGENCE", "Due Diligence"),
                    ("CLOSING", "Closing"),
                    ("ACQUIRED", "Acquired"),
                    ("RENOVATION", "Renovation"),
                    ("STABILIZED", "Stabilized"),
                ],
                db_index=True,
                default="DISCOVERED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pipelineproperty",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("KILLED", "Killed"),
                    ("ON_HOLD", "On Hold"),
                    ("ACQUIRED", "Acquired"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
