# Generated by Django 6.0.7 on 2026-07-11 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_add_location_fields_to_pipeline_property"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pipelineproperty",
            index=models.Index(
                fields=["source_type", "source_id"], name="idx_pp_source_type_source_id"
            ),
        ),
    ]
