# Generated by Django 6.0.7 on 2026-07-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0045_add_indexes_pipeline_and_foreclosure"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSourceHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_name", models.CharField(max_length=64, unique=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("record_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("error", "Error"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Data Source Health",
                "verbose_name_plural": "Data Source Health",
                "ordering": ["source_name"],
            },
        ),
    ]
