# Generated by Django 6.0.7 on 2026-08-20 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_data_source_health"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasourcehealth",
            name="consecutive_errors",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ScreeningCriteriaVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "criteria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="core.screeningcriteria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Screening Criteria Version",
                "verbose_name_plural": "Screening Criteria Versions",
                "ordering": ["-created_at"],
            },
        ),
    ]
