# Generated by Django 6.0.7 on 2026-08-21 13:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_add_consecutive_errors_and_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapExItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("roof", "Roof"),
                            ("hvac", "HVAC"),
                            ("water_heater", "Water Heater"),
                            ("appliances", "Appliances"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                (
                    "replacement_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("useful_life_years", models.PositiveIntegerField()),
                ("age_years", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "prop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capex_items",
                        to="core.property",
                    ),
                ),
            ],
            options={
                "ordering": ["component_type"],
                "unique_together": {("prop", "component_type")},
            },
        ),
    ]
