# Generated by Django 6.0.7 on 2026-08-21 14:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_add_consecutive_errors_and_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancingScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loan_type",
                    models.CharField(
                        choices=[
                            ("conventional", "Conventional"),
                            ("dscr", "DSCR Loan"),
                            ("seller_financing", "Seller Financing"),
                            ("other", "Other"),
                        ],
                        default="conventional",
                        max_length=32,
                    ),
                ),
                (
                    "ltv_pct",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Loan-to-value as fraction (e.g., 0.75 for 75%)",
                        max_digits=5,
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Annual interest rate as fraction (e.g., 0.075 for 7.5%)",
                        max_digits=5,
                    ),
                ),
                ("term_years", models.PositiveIntegerField(default=30)),
                (
                    "closing_costs",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "prop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financing_scenarios",
                        to="core.property",
                    ),
                ),
            ],
            options={
                "ordering": ["loan_type"],
                "unique_together": {("prop", "loan_type")},
            },
        ),
    ]
