# Generated by Django 6.0.7 on 2026-08-21 15:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0048_capexitem"),
        ("core", "0048_financingscenario"),
    ]

    operations = []
