# Generated by Django 6.0.7 on 2026-08-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_merge_0048_capexitem_0048_financingscenario"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metro_area",
                    models.CharField(
                        db_index=True,
                        help_text="Metropolitan Statistical Area name (e.g., 'Dallas-Fort Worth-Arlington, TX')",
                        max_length=255,
                    ),
                ),
                (
                    "indicator_type",
                    models.CharField(
                        choices=[
                            ("median_price", "Median Home Price"),
                            ("dom", "Days on Market"),
                            ("months_supply", "Months of Supply"),
                            ("price_to_income", "Price-to-Income Ratio"),
                            ("rent_growth_yoy", "Rent Growth Year-over-Year"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Indicator value (e.g., 425000.00 for median price, 28.0000 for DOM)",
                        max_digits=18,
                    ),
                ),
                (
                    "date_recorded",
                    models.DateField(
                        db_index=True,
                        help_text="Date this indicator value was recorded",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Data source (e.g., 'zillow', 'census', 'bls', 'fred', 'manual')",
                        max_length=64,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional context or methodology notes",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date_recorded", "metro_area", "indicator_type"],
                "indexes": [
                    models.Index(
                        fields=["metro_area", "date_recorded"],
                        name="core_market_metro_a_045f3e_idx",
                    ),
                    models.Index(
                        fields=["indicator_type", "date_recorded"],
                        name="core_market_indicat_d192ce_idx",
                    ),
                ],
                "unique_together": {("metro_area", "indicator_type", "date_recorded")},
            },
        ),
    ]
