# Generated by Django 6.0.7 on 2026-08-29 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_marketindicator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capexitem",
            name="useful_life_years",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
